//! C02 subject definitions.

use super::Subject;

pub static ALL: &[Subject] = &[
    Subject {
        exercise: "ex00",
        function: "ft_strcpy",
        c_prototype: "char\t*ft_strcpy(char *dest, char *src);",
        files: &["ft_strcpy.c"],
        description: "Copy src into dest.",
        tests: &[],
    },
    Subject {
        exercise: "ex01",
        function: "ft_strncpy",
        c_prototype: "char\t*ft_strncpy(char *dest, char *src, unsigned int n);",
        files: &["ft_strncpy.c"],
        description: "Copy at most n chars from src to dest.",
        tests: &[],
    },
    Subject {
        exercise: "ex02",
        function: "ft_str_is_alpha",
        c_prototype: "int\tft_str_is_alpha(char *str);",
        files: &["ft_str_is_alpha.c"],
        description: "Return 1 if string contains only alphabetic chars.",
        tests: &[],
    },
    Subject {
        exercise: "ex03",
        function: "ft_str_is_numeric",
        c_prototype: "int\tft_str_is_numeric(char *str);",
        files: &["ft_str_is_numeric.c"],
        description: "Return 1 if string contains only digits.",
        tests: &[],
    },
    Subject {
        exercise: "ex04",
        function: "ft_str_is_lowercase",
        c_prototype: "int\tft_str_is_lowercase(char *str);",
        files: &["ft_str_is_lowercase.c"],
        description: "Return 1 if string contains only lowercase chars.",
        tests: &[],
    },
    Subject {
        exercise: "ex05",
        function: "ft_str_is_uppercase",
        c_prototype: "int\tft_str_is_uppercase(char *str);",
        files: &["ft_str_is_uppercase.c"],
        description: "Return 1 if string contains only uppercase chars.",
        tests: &[],
    },
    Subject {
        exercise: "ex06",
        function: "ft_str_is_printable",
        c_prototype: "int\tft_str_is_printable(char *str);",
        files: &["ft_str_is_printable.c"],
        description: "Return 1 if string contains only printable chars.",
        tests: &[],
    },
    Subject {
        exercise: "ex07",
        function: "ft_strupcase",
        c_prototype: "char\t*ft_strupcase(char *str);",
        files: &["ft_strupcase.c"],
        description: "Convert string to uppercase in place.",
        tests: &[],
    },
    Subject {
        exercise: "ex08",
        function: "ft_strlowcase",
        c_prototype: "char\t*ft_strlowcase(char *str);",
        files: &["ft_strlowcase.c"],
        description: "Convert string to lowercase in place.",
        tests: &[],
    },
    Subject {
        exercise: "ex09",
        function: "ft_strcapitalize",
        c_prototype: "char\t*ft_strcapitalize(char *str);",
        files: &["ft_strcapitalize.c"],
        description: "Capitalize words in place.",
        tests: &[],
    },
    Subject {
        exercise: "ex10",
        function: "ft_strlcpy",
        c_prototype: "unsigned int\tft_strlcpy(char *dest, char *src, unsigned int size);",
        files: &["ft_strlcpy.c"],
        description: "Copy string with size-limited destination buffer.",
        tests: &[],
    },
    Subject {
        exercise: "ex11",
        function: "ft_putstr_non_printable",
        c_prototype: "void\tft_putstr_non_printable(char *str);",
        files: &["ft_putstr_non_printable.c"],
        description: "Print string, escaping non-printable bytes.",
        tests: &[],
    },
    Subject {
        exercise: "ex12",
        function: "ft_print_memory",
        c_prototype: "void\t*ft_print_memory(void *addr, unsigned int size);",
        files: &["ft_print_memory.c"],
        description: "Hexdump memory region in canonical 42 format.",
        tests: &[],
    },
];
